= Barberousse - Remote Secrets Editor

image:https://gist.githubusercontent.com/zeapo/2afd80cabc820156fd34f5888f207202/raw/d90618f2cc72fb62436303caba1a46c0282ca87a/barblogo.svg[width=120,align=center]

A project aimed to avoid downloading secrets from remote providers (support only AWS Secret Manager for the moment).
Opens an editor with the content of the secret readily editable, upon save & exit, the secret is automatically uploaded
and a new version created remotely. This way, no need to use common bad-practices such as versionning secrets in a VCS
or worst, storing them on your machine and sending them via slack :)

NOTE: This project is at its earliest stage a project can be, i.e. a proof of concept that might or not develop into a full
fledged project.

== Printing
Cat your secret in a nice format
image:https://gist.githubusercontent.com/zeapo/dc584b68baa0e735670ad87b4754debe/raw/227c8de2a054dd844d67b01893bc954aca951157/barbcat.svg[]

== Editing
Allows you to edit a remote secret without saving it on disk (a temp file is created though... a more secure way to handle temp files will come in the future). You can use different formats to edit your secret (json, yaml, plain text):
image:https://gist.githubusercontent.com/zeapo/e6e468331bfb3d2785237a93d782685d/raw/f652a19d1e86e96453bac4593055041516ea08f6/barbedit.svg[]

== MVP WishList

When all of the following is checked, it could be said that we've got our 0.1 MVP 🎂🎂🎂

* [ ] General
** [ ] Support selecting profiles and regions (env variables are supported though)
** [ ] others ?
* [-] Editing
** [x] Edit JSON, YAML, text
** [x] Edit JSON using YAML (default behavior)
** [x] Edit <format> using <another format>
** [ ] Edit basic secrets
** [ ] Create a secret if not exist
** [ ] Edit Secret metadata
** [ ] Templating support, allow the user to create a secret from a template
** [x] Custom editor selection, pass `--editor`
** [ ] Edit secret's metadata
* [ ] Printing
** [x] Cat the content of a secret in one or many other formats
** [ ] Get a single key from a secret
** [ ] Print secret's metadata
* [ ] Copy
** [ ] Duplicate a secret (and open an editor before saving the copy)
** [ ] Support cross account / region / profiles copy



